hw_10/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

hw_10/hw_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>', views.main, name="root_paginate"),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('add-author/', views.add_author, name='add_author'),
    path('add-quote/', views.add_quote, name='add_quote')
]

hw_10/hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_10/hw_project/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw_10/hw_project/quotes/forms.py
from django import forms
from .models import Author, Quote


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        widgets = {
            'born_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fullname'].required = True
        self.fields['born_date'].required = False
        self.fields['born_location'].required = False
        self.fields['description'].required = False

    def clean_fullname(self):
        fullname = self.cleaned_data.get('fullname')
        if Author.objects.filter(fullname=fullname).exists():
            raise forms.ValidationError("An author with this fullname already exists.")
        return fullname


class QuoteForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter tags separated by comma'}), required=False)

    class Meta:
        model = Quote
        fields = ['quote', 'author']

    def clean_tags(self):
        tags_input = self.cleaned_data.get('tags', '')
        if isinstance(tags_input, str):
            tags = [tag.strip() for tag in tags_input.split(',')]
        elif isinstance(tags_input, list):
            tags = [tag.strip() for tag in tags_input if isinstance(tag, str)]
        else:
            tags = []
        return tags

hw_10/hw_project/quotes/views.py
# from .utils import get_mongodb
from django.core.paginator import Paginator
from .models import Quote
from django.shortcuts import render, get_object_or_404, redirect
from .models import Author
from .forms import AuthorForm, QuoteForm
from .models import Tag


# def main(request, page = 1):
#     db = get_mongodb()
#     quotes = db.quotes.find()
#     per_page = 10
#     paginator = Paginator(list(quotes), per_page)
#     quotes_on_page = paginator.page(page)
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def main(request, page=1):
    quotes = Quote.objects.all()

    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/author_detail.html', {'author': author})


def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to a success page or back to the main page
            return redirect('quotes:root')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            # Save quote and associate tags
            quote = form.save(commit=False)
            quote.save()
            for tag_name in form.cleaned_data['tags']:
                tag, _ = Tag.objects.get_or_create(name=tag_name)
                quote.tags.add(tag)

            return redirect('quotes:root')
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

hw_10/hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}
{% block content %}
<div class="container">
    <h2>Add New Author</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'quotes:root' %}" class="btn btn-primary">Back to Quotes</a>

    </form>
</div>
{% endblock %}

hw_10/hw_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}
{% block content %}
  <h2>Add New Quote</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'quotes:root' %}" class="btn btn-primary">Back to Quotes</a>

  </form>
{% endblock %}

hw_10/hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}
{% block content %}
<html lang="en">

    <h2>{{ author.fullname }}</h2>
    <p>Born Date: {{ author.born_date }}</p>
    <p>Born Location: {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>

    <a href="{% url 'quotes:root' %}">Back to Quotes</a>
</body>
</html>
{% endblock %}

hw_10/hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework 10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                        <span>Welcome, {{ user.username }}!  </span>
                </p>
                <p>
                        <a href="/users/logout" class="btn btn-primary">Logout</a>
                        <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                        <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                    {% else %}
                        <a href="/users/signup" class="btn btn-primary">Sign Up</a>
                        <a href="/users/login" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% block content %} {% endblock %}
    </div>
</body>
</html>

hw_10/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname}}</small>
                <a href="{% url 'quotes:author_detail' quote.author.id %}"> (about) </a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                    <abutton class="tag" data-tag="{{ tag.name }}">{{ tag.name }}</abutton>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">
                <li class="previous {% if not quotes.has_previous %}disabled{% endif %}">
                    {% if quotes.has_previous %}
                        <a href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">
                            <span aria-hidden="true">← Previous</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">← Previous</span>
                    {% endif %}
                </li>

                <li class="next {% if not quotes.has_next %}disabled{% endif %}">
                    {% if quotes.has_next %}
                        <a href="{% url 'quotes:root_paginate' quotes.next_page_number %}">
                            <span aria-hidden="true">Next →</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">Next →</span>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}